<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot();  // TODO: change the autogenerated stub

        static::created(function (\app\User $user) {
            $user->profile()->create([
                'name' => $user->username
            ]);
        });

        // Send welcome Email from here
    }

    public function profile() {
        return $this->hasOne(Profile::class);
    }

    public function role() {
        return $this->belongsTo(Role::class);
    }

    public function song() {
        return $this->hasMany(Song::class);
    }

}
